In [1]:
import pandas as pd
import re
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
with open("edgar_allan_poe.txt") as eap:
    edgar = eap.readlines()
with open("robert_frost.txt") as rf:
    robert = rf.readlines()

# edgar = edgar.split("\n\n")
# robert = robert.split("\n\n")

In [3]:
labels = []
input_data = []
for i,j in enumerate(edgar):
    j = j.rstrip().lower()
    edgar[i] = re.sub("[^a-z ]","",j)
    if len(edgar[i]) != 0:
        labels.append(0)
        input_data.append(edgar[i])
 
for i,j in enumerate(robert):
    j = j.rstrip().lower()
    robert[i] = re.sub("[^a-z ]","",j)
    if len(robert[i])!=0:
        labels.append(1)
        input_data.append(robert[i])

In [4]:
len(input_data)

2154

In [5]:
X_train,X_test,y_train,y_test = train_test_split(input_data,labels,test_size=0.2,random_state=42)

In [6]:
len(X_train),len(X_test)

(1723, 431)

In [7]:
idx =1
word2idx = {"<unk>":0}
for i in X_train:
    for j in i.split():
        if j not in word2idx:
            word2idx[j]=idx
            idx+=1

In [8]:
word2idx

{'<unk': 0,
 'and': 1,
 'many': 2,
 'must': 3,
 'have': 4,
 'seen': 5,
 'him': 6,
 'make': 7,
 'with': 8,
 'flowers': 9,
 'in': 10,
 'her': 11,
 'lap': 12,
 'until': 13,
 'they': 14,
 'fade': 15,
 'what': 16,
 'signify': 17,
 'a': 18,
 'donkeys': 19,
 'cars': 20,
 'bottle': 21,
 'son': 22,
 'mother': 23,
 'can': 24,
 'common': 25,
 'table': 26,
 'rear': 27,
 'if': 28,
 'the': 29,
 'wish': 30,
 'hadnt': 31,
 'been': 32,
 'too': 33,
 'strong': 34,
 'me': 35,
 'town': 36,
 'that': 37,
 'is': 38,
 'no': 39,
 'more': 40,
 'on': 41,
 'thine': 42,
 'own': 43,
 'upturnd': 44,
 'alas': 45,
 'sorrow': 46,
 'heavy': 47,
 'iron': 48,
 'bells': 49,
 'front': 50,
 'of': 51,
 'one': 52,
 'hall': 53,
 'id': 54,
 'left': 55,
 'hitched': 56,
 'single': 57,
 'leaf': 58,
 'was': 59,
 'bough': 60,
 'unembodied': 61,
 'essence': 62,
 'hiss': 63,
 'spray': 64,
 'it': 65,
 'will': 66,
 'go': 67,
 'hard': 68,
 'john': 69,
 'he': 70,
 'do': 71,
 'you': 72,
 'not': 73,
 'mind': 74,
 'certain': 75,
 'coolness': 7

In [9]:
len(word2idx)

2603

In [10]:
X_train

['and many must have seen him make',
 'with flowers in her lap until they fade',
 'what signify a donkeys cars and bottle',
 'son mother can make a common table rear',
 'if the wish hadnt been too strong in me',
 'and in a town that is no more a town',
 'and on thine own upturnd alas in sorrow',
 'the heavy iron bells',
 'in front of one town hall id left him hitched',
 'a single leaf was on a bough',
 'the unembodied essence and no more',
 'with the hiss of spray',
 'it will go hard with john what will he do',
 'you must not mind a certain coolness from him',
 'thy heart thy heart i wake and sigh',
 'there open temples open graves',
 'had checked the pace',
 'i made him do it for me in the dark',
 'john hall touch me not if he knows his friends',
 'we noted not the dim lake of auber ',
 'that gave out in return for the lovelight',
 'hell sort of swear the time away hes awful',
 'along that wilderness of glass',
 'a shelfs for a clock or vase or picture',
 'that doesnt exist',
 'in the

In [11]:
train_data_int=[]
text_data_int=[]
for i in X_train:
    train_data_int.append([word2idx.get(k,0) for k in i.split()])
for i in X_test:
    text_data_int.append([word2idx.get(k,0) for k in i.split()])

In [12]:
X_test[:10]

['beyond where they were was a shattered seedpod',
 'and wheres john',
 'according as he feared to risk',
 'of what in other worlds shall be and given',
 'to the place where john has been cutting trees',
 'wings until they trailed in the dust ',
 'in rain tomorrow shall we if it rains',
 'however far you must go for bricks',
 'my fingers are about all ive the use of',
 'and sorry i could not travel both']

In [13]:
text_data_int[:10]

[[605, 157, 14, 154, 59, 18, 0, 0],
 [1, 0, 69],
 [0, 149, 70, 1554, 169, 0],
 [51, 16, 10, 971, 989, 734, 328, 1, 803],
 [169, 29, 518, 157, 69, 499, 32, 0, 188],
 [1996, 13, 14, 2269, 10, 29, 1066],
 [10, 410, 0, 734, 97, 28, 65, 0],
 [164, 238, 72, 3, 67, 91, 0],
 [220, 1625, 549, 578, 145, 809, 29, 2420, 51],
 [1, 474, 80, 407, 73, 0, 1347]]

In [14]:
v= len(word2idx)

In [15]:
# initialize A and pi for both classes
A0 = np.ones((v,v))
pi0 = np.ones(v)

A1 = np.ones((v,v))
pi1 = np.ones(v)

In [16]:
def compute_counts(data_int,A,pi):
    for tokens in data_int:
        last_idx = None
        for idx in tokens:
            if last_idx is None:
                pi[idx]+=1
            else:
                A[last_idx,idx] += 1
            last_idx = idx
            
compute_counts([k for k,y in zip(train_data_int,y_train) if y==0],A0,pi0)
compute_counts([k for k,y in zip(train_data_int,y_train) if y==1],A1,pi1)

In [17]:
A0

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [18]:
v

2603

In [19]:
A0 /= A0.sum(axis=1,keepdims=True)
pi0 /= pi0.sum()

A1 /= A1.sum(axis=1,keepdims=True)
pi1 /= pi1.sum()

In [20]:
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [21]:
count0 = sum(y == 0 for y in y_train)
count1 = sum(y == 1 for y in y_train)
total = len(y_train)
p0 = count0/total
p1 = count1/total
logp0 = np.log(p0)
logp1 = np.log(p1)
p0,p1

(0.3308183401044689, 0.669181659895531)

In [22]:
class Classifier:
    def __init__(self, logAs, logpis, logpriors):
        self.logAs = logAs
        self.logpis = logpis
        self.logpriors = logpriors
        self.K = len(logpriors)

    def _compute_log_likelihood(self, input_, class_):
        logA = self.logAs[class_]
        logpi = self.logpis[class_]
        last_idx = None
        logprob =0
        for idx in input_:
            if last_idx is None:
                logprob +=logpi[idx]
            else:
                logprob += logA[last_idx,idx]
            last_idx = idx

        return logprob

    def predict(self, inputs):
        predictions = np.zeros(len(inputs))
        for i, input_ in enumerate(inputs):
            posteriors = [self._compute_log_likelihood(input_,c) + self.logpriors[c] for c in range(self.K)]
            pred = np.argmax(posteriors)
            predictions[i] = pred
        return predictions

In [23]:
clf = Classifier([logA0, logA1], [logpi0, logpi1], [logp0, logp1])

In [24]:
Ptrain = clf.predict(train_data_int)
print(f"Test accuracy: {np.mean(Ptrain==y_train)*100:.2f}%")

Test accuracy: 99.59%


In [25]:
from sklearn.metrics import confusion_matrix, f1_score
cm = confusion_matrix(y_train, Ptrain)
cm

array([[ 563,    7],
       [   0, 1153]], dtype=int64)

In [26]:
Ptest = clf.predict(text_data_int)
print(f"Train accuracy: {np.mean(Ptest==y_test)*100:.2f}%")

Train accuracy: 84.45%


In [27]:
cm = confusion_matrix(y_test, Ptest)
cm

array([[ 85,  63],
       [  4, 279]], dtype=int64)

In [28]:
f1_score(y_train, Ptrain)

0.9969736273238219

In [29]:
f1_score(y_test, Ptest)

0.8928